#ifndef COSTANTI_H_
#define COSTANTI_H_

#define LARGHEZZA_FINESTRA 80
#define LUNGHEZZA_FINESTRA 25
#define MAX_PARTITE_SALVATE 5
#define DIM_MAX_STRINGA 20
#define PERCENTUALE_DIFFICOLTA_FACILE 45 / 100
#define PERCENTUALE_DIFFICOLTA_MEDIA 35 / 100
#define PERCENTUALE_DIFFICOLTA_DIFFICILE 25 / 100
#define DIM_GRIGLIA_PICCOLA 4
#define DIM_GRIGLIA_STANDARD 9
#define DIM_GRIGLIA_GRANDE 16
#define DIFFICOLTA_STANDARD 0
#define DIFFICOLTA_MEDIA 1
#define DIFFICOLTA_DIFFICILE 2

typedef enum {
	CHAR_0 = 48,
	CHAR_1 = 49,
	CHAR_2 = 50,
	CHAR_3 = 51,
	CHAR_4 = 52,
	CHAR_5 = 53,
	CHAR_6 = 54,
	CHAR_7 = 55,
	CHAR_8 = 56,
	CHAR_9 = 57,
	CHAR_A = 65,
	CHAR_G = 71,
	CHAR_a = 97,
	CHAR_z = 122

} ASCII_CODE;

#endif
