#ifndef COSTANTI_INTERFACCE_H_
#define COSTANTI_INTERFACCE_H_

#define LARGHEZZA_FINESTRA 80
#define LUNGHEZZA_FINESTRA 25
#define SPAZIO_RISERVATO_GRIGLIA_INTERFACCIA_X 50
#define SPAZIO_RISERVATO_GRIGLIA_INTERFACCIA_Y 22
#define BANNER_ERRORE_POS_X 1
#define BANNER_ERRORE_POS_Y 24

#endif
