#ifndef COSTANTI_H_
#define COSTANTI_H_

#define MAX_PARTITE_SALVATE 5
#define DIM_MAX_STRINGA 20
#define PERCENTUALE_DIFFICOLTA_FACILE 45 / 100
#define PERCENTUALE_DIFFICOLTA_MEDIA 35 / 100
#define PERCENTUALE_DIFFICOLTA_DIFFICILE 25 / 100
#define DIM_GRIGLIA_PICCOLA 4
#define DIM_GRIGLIA_STANDARD 9
#define DIM_GRIGLIA_GRANDE 16
#define DIFFICOLTA_STANDARD 0
#define DIFFICOLTA_MEDIA 1
#define DIFFICOLTA_DIFFICILE 2

#endif
