#ifndef COSTANTI_H_
#define COSTANTI_H_

#define LARGHEZZA_FINESTRA 80
#define LUNGHEZZA_FINESTRA 25
#define MAX_PARTITE_SALVATE 5
#define DIM_MAX_STRINGA 20
#define PERCENTUALE_DIFFICOLTA_FACILE 45 / 100
#define PERCENTUALE_DIFFICOLTA_MEDIA 35 / 100
#define PERCENTUALE_DIFFICOLTA_DIFFICILE 25 / 100
#define DIM_GRIGLIA_PICCOLA 4
#define DIM_GRIGLIA_STANDARD 9
#define DIM_GRIGLIA_GRANDE 16
#define DIFFICOLTA_STANDARD 0
#define DIFFICOLTA_MEDIA 1
#define DIFFICOLTA_DIFFICILE 2
#define ANSI_COLOR_BLACK "\x1b[30m"
#define ANSI_COLOR_RED "\x1b[31m"
#define ANSI_COLOR_GREEN "\x1b[32m"
#define ANSI_COLOR_YELLOW "\x1b[33m"
#define ANSI_COLOR_BLUE "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN "\x1b[36m"
#define ANSI_COLOR_WHITE "\x1b[37m"
#define ANSI_COLOR_RESET "\x1b[m"

typedef enum {
	CHAR_0 = 48,
	CHAR_1 = 49,
	CHAR_2 = 50,
	CHAR_3 = 51,
	CHAR_4 = 52,
	CHAR_5 = 53,
	CHAR_6 = 54,
	CHAR_7 = 55,
	CHAR_8 = 56,
	CHAR_9 = 57,
	CHAR_A = 65,
	CHAR_G = 71,
	CHAR_a = 97,
	CHAR_z = 122,
	TASTO_ESC = 27
} ASCII_CODE;

#endif
