#ifndef GESTIRE_ERRORI_H_
#define GESTIRE_ERRORI_H_

#include "utils.h"

#define ERRORE_NOME_FILE "PRIMA DI PROSEGUIRE DEVI INSERIRE IL NOME DELLA PARTITA"
#define ERRORE_INPUT_ERRATI "ATTENZIONE: INPUT NON VALIDO"
#define ERRORE_VALORE_NON_MODIFICABILE "ATTENZIONE: VALORE NON MODIFICABILE"
#define ERRORE_CARICAMENTO "ATTENZIONE: HAI SELEZIONATO UNO SLOT VUOTO"
#define ERRORE_SALVATAGGIO ""

void stampare_banner_errore(int x, int y, int dim, char* messaggio_errore);

#endif
