#ifndef MESSAGGI_ERRORI_H_
#define MESSAGGI_ERRORI_H_

#define ERRORE_CARICAMENTO "ATTENZIONE: HAI SELEZIONATO UNO SLOT VUOTO"
#define ERRORE_INPUT_ERRATI "ATTENZIONE: INPUT NON VALIDO"
#define ERRORE_NOME_FILE "PRIMA DI PROSEGUIRE DEVI INSERIRE IL NOME DELLA PARTITA"
#define ERRORE_SALVATAGGIO "ATTENZIONE: SALVATAGGIO NON RIUSCITO"
#define ERRORE_VALORE_NON_MODIFICABILE "ATTENZIONE: VALORE NON MODIFICABILE"

#endif
